feature/storage-implementation
WalletConnect-Labs/WalletConnectKotlinV2 pull request #107
Opened 2021-11-27 06:07 UTC by TalhaAli00

2021-11-27 12:26 UTC, ligi requested changes
small nit

2021-11-27 12:26 UTC, ligi commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/common/network/adapters/TopicAdapterTest.kt
> +        val expected = """"${topic.value}""""
```suggestion
        val expected = topic.value
```

2021-11-29 03:03 UTC, TalhaAli00 commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/common/network/adapters/TopicAdapterTest.kt
> +        val expected = """"${topic.value}""""
updated logic. We want to have the value between quotes

2021-11-29 07:32 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepository.kt
> +//            .lifecycle(AndroidLifecycle.ofApplicationForeground(application)) // TODO: Maybe have debug version of scarlet w/o application and release version of scarlet w/ application once DI is s
Uncomment

2021-11-29 07:37 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
>      private var isConnected = MutableStateFlow(false) // TODO: Maybe replace with an enum
You can resolve this TODO comment and add enum instead of flag

2021-11-29 07:40 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        storageRepository = StorageRepository(null, engine.application)
Why do you pass `null`?

2021-11-29 07:43 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                }
I would add the named parameter
``` .onEach { session ->
                    relayRepository.subscribe(session.topic!!)
                }
```

2021-11-29 07:44 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +            .filter { isOnline -> isOnline }  // TODO: Update once enum is in place
It can be changed to enum

2021-11-29 07:59 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        storageRepository.updateStatusToSessionApproval(peerPublicKey.keyAsHex, selfPublicKey.keyAsHex, settledSession.topic.value, proposal.accounts, expiry.seconds)
You can just pass `settledSequence` instead of the 5 params

2021-11-29 08:02 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        relayRepository.publish(Topic(topic), encryptedMessage) { result ->
When `reject` the session proposal, we should delete the current pending session from DB

2021-11-29 08:04 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        storageRepository.delete(selfPublic.keyAsHex)
I'm wondering why did you decide to use public key as session primary key. IMO it should be topic.

Topic B -> Pairing
Topic D -> Session

2021-11-29 08:06 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        //TODO update the session in local storage
You should update session in DB with the new state

2021-11-29 08:07 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        //TODO update session in local storage
You should update session in DB with the new permissions

2021-11-29 08:09 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +            storageRepository.delete(selfPublic.keyAsHex)
Same, there should be the topic instead of the publicKey

2021-11-29 08:09 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
>              //TODO Add subscriptionId from local storage + Delete all data from local storage coupled with given session
Pls update the TODO comment

2021-11-29 08:12 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +    private val driver = sqliteDriver ?: AndroidSqliteDriver(
I thought that the goal is to have DB storage decoupled from Android.  To support both JVM and Android.

2021-11-29 08:13 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +    val sessions = sessionDatabase.sessionQueries.getSessionDaoWithMetadata(mapper = this@StorageRepository::mapSessionsDaoWithMetadataToSession)
Adding the type would be nice here

2021-11-29 08:14 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +    fun updateStatusToSessionApproval(keyToSearch: String, selfPublicKey: String, updateTopic: String, listOfAccounts: List<String>, expiry: Long) {
SettledSession instead of so many params?

2021-11-29 09:05 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +        return if (status == SequenceStatus.PENDING) {
Instead of this flag, I would just return the SessionEntity and then map it to engine Session.

Session returned by this function should only differ in case of the `status`. Both pending and the settled should have the same parameters. For example, when you return the Session.Success(), the permissions are missing.

Also, I think it's better not to mix the relay models with the DB I would rather have here better separation of concerns.

 Let me know what do you think.

2021-11-29 09:24 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        // Automatically resubscribe to any approved sessions in the DB
Instead of comment, I would rather wrap it with method and add meaningful name.

2021-11-29 09:26 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                    relayRepository.subscribe(it.topic!!)
Did you test this piece of code? I've setup a session, then killed the app, relaunch it and it didn't work.

2021-11-29 09:46 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                onSuccess = { with(proposal) { onSuccess(EngineData.SettledSession(icon, name, url, settledSession.topic.value)) } },
+ I think we should call `storageRepository.updateStatusToSessionApproval()` in the `onSuccess` callback

2021-11-29 09:53 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +
Every time, that we the session is settled and we're gonna use it, we should check if under given topic session exists. If not, we should throw an error. 

Not sure if it's the scope of current PR, let me know.

2021-11-29 09:58 UTC, chaak commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepositoryTest.kt
> +
I cannot run those tests:
`No instrumentation registered! Must run under a registering instrumentation.`

Did you have the same issue?

2021-11-29 10:00 UTC, chaak commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepositoryTest.kt
> +}
<img width="400" alt="Screenshot 2021-11-29 at 10 59 02" src="https://user-images.githubusercontent.com/23366251/143847075-3462ee4e-aab6-4e3c-b118-f448f6e64936.png">

I noticed that there is another directory created, just wanna be sure if it's on purpose?

2021-11-29 10:01 UTC, chaak requested changes
All comments from my side. In case of any questions we can have a call

2021-11-29 10:52 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                onSuccess = { with(proposal) { onSuccess(EngineData.SettledSession(icon, name, url, settledSession.topic.value)) } },
IMO we should change the status of pending session to settled once we got the acknowledgement

2021-11-29 13:17 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepository.kt
> +//            .lifecycle(AndroidLifecycle.ofApplicationForeground(application)) // TODO: Maybe have debug version of scarlet w/o application and release version of scarlet w/ application once DI is s
done

2021-12-01 07:25 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +    private val driver = sqliteDriver ?: AndroidSqliteDriver(
Eventually, yes. Atm, we only care about the Android platform. We will just need to add the JVM driver once we get to doing it

2021-12-01 07:27 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +            storageRepository.delete(selfPublic.keyAsHex)
done

2021-12-01 07:33 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +    fun updateStatusToSessionApproval(keyToSearch: String, selfPublicKey: String, updateTopic: String, listOfAccounts: List<String>, expiry: Long) {
I'm of the mind set only pass what you need and nothing extra. It keeps the function focused and avoids the possibility of being abused for other stuff

2021-12-01 07:33 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +        return if (status == SequenceStatus.PENDING) {
did something similar to your suggestion

2021-12-01 14:13 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        storageRepository = StorageRepository(null, engine.application)
This allows us to pass different implementations of the SqlDriver. I did null so the StorageRepository will default to the Android implementation but the Unit Test will pass it's own SqlDriver

2021-12-01 14:15 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                }
replaced with an internal Session object

2021-12-01 15:39 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        storageRepository.updateStatusToSessionApproval(peerPublicKey.keyAsHex, selfPublicKey.keyAsHex, settledSession.topic.value, proposal.accounts, expiry.seconds)
I'm not a fan of passing whole object with more information than is needed. The caller of functions has the most knowledge about the data being passed. The `StorageRepository` is decoupled from any objects

2021-12-01 15:57 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        // Automatically resubscribe to any approved sessions in the DB
Moved to a private function

2021-12-01 15:58 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                    relayRepository.subscribe(it.topic!!)
I am getting logs showing that it works

2021-12-01 16:02 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +
I don't understand what we could do here? Please create an issue and we can address it along with the other errors that we need to handle

2021-12-01 17:33 UTC, TalhaAli00 commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepositoryTest.kt
> +
No, I didn't run into any similar. I had to remove the old tests with the DB changes that were made so I'll be going back and adding new tests later

2021-12-01 17:34 UTC, TalhaAli00 commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepositoryTest.kt
> +}
yes, this was on purpose. It's to make sure DAO classes and the VO classes are in the same parent directory

2021-12-01 17:35 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                onSuccess = { with(proposal) { onSuccess(EngineData.SettledSession(icon, name, url, settledSession.topic.value)) } },
good idea. Updated

2021-12-02 08:58 UTC, chaak requested changes
Couple more comments

2021-12-02 08:58 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        val metaData = storageRepository.getMetaData()
This one is unused, should be deleted

2021-12-02 08:58 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +    fun delete(selfPublicKeyString: String) {
`selfPublicKeyString` -> `topic`

2021-12-02 08:58 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                            proposal.topic,
When we set status of session to `Settled`, only settledTopic (Topic D) is needed.  `proposal.topic` (Topic C) is not needed here.

2021-12-02 08:58 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +        private const val FAILED_INSERT_ID = -1L
Not used

2021-12-02 08:58 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +        sessionDatabase.sessionDaoQueries.insertSession(
I got error when inserting the pending session after scanning the qr code:

<img width="1435" alt="Screenshot 2021-12-02 at 09 57 33" src="https://user-images.githubusercontent.com/23366251/144389887-96188299-b237-433b-b1d7-14ff9b3d87c6.png">

2021-12-02 13:14 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        val metaData = storageRepository.getMetaData()
done

2021-12-02 13:14 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +    fun delete(selfPublicKeyString: String) {
done

2021-12-02 13:17 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                            proposal.topic,
we need the old topic to find the session. If you go into the SQL statement, you'll see that the topic is being updated to the settled topic once a session has been found

2021-12-02 13:18 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +        private const val FAILED_INSERT_ID = -1L
done
=

2021-12-02 13:19 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/storage/StorageRepository.kt
> +        sessionDatabase.sessionDaoQueries.insertSession(
you might have to clear the data from the device if you've run the code before. Since there was a schema change and no migration, it's possible that the old table is still on your device

2021-12-02 14:05 UTC, chaak approved these changes
Thanks for discussions

2021-12-03 04:32 UTC, merged