Feature/implement peer responses
WalletConnect-Labs/WalletConnectKotlinV2 pull request #117
Opened 2021-12-06 08:35 UTC by chaak

2021-12-06 15:42 UTC, TalhaAli00 commented on sample/src/main/java/org/walletconnect/example/wallet/WalletViewModel.kt
> +import android.util.Log
Remove since it's not being used

2021-12-06 15:48 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/client/WalletConnectClientData.kt
> +        val topic: String,
Remove unused comma

2021-12-06 16:15 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/JsonRpcSerializing.kt
> +interface JsonRpcSerializing {
Do we need an interface? There's only one implementation

2021-12-06 18:45 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/crypto/CryptoManager.kt
>      fun removeKeys(tag: String)
just curious, is there a reason for spacing the functions like this?

2021-12-06 18:52 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/utils/ClientJsonRpcSerializer.kt
> +            JsonRpcMethod.WC_SESSION_NOTIFICATION -> tryDeserialize<PostSettlementSession.SessionNotification>(json)?.params
move `tryDeserialize` into this function and make it private

2021-12-06 18:52 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/utils/ClientJsonRpcSerializer.kt
> +            is JsonRpcResponse -> trySerialize(payload)
move `trySerialize` into this function and make it private

2021-12-06 18:54 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/utils/JsonRpcMethod.kt
>  object JsonRpcMethod {
move these into ClientJsonRpcSerializer so they're close to where they're used

2021-12-06 19:25 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/utils/ClientJsonRpcSerializer.kt
> +object ClientJsonRpcSerializer {
instead of having `ClientJsonRpcSerializer`, just move `deserialize` and `serialize` into JsonRpcSerializer

2021-12-07 03:09 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/JsonRpcSerializer.kt
> +class JsonRpcSerializer : JsonRpcSerializing {
Move `trySerialize` and `tryDeserialize` into this class

2021-12-07 03:13 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +import okhttp3.internal.notify
remove if it's not being used

2021-12-07 03:15 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/util/UtilFunctions.kt
> +private fun cleanHexPrefix(input: String): String =
what is this doing?

2021-12-07 03:16 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/serailising/Serializer.kt
> +inline fun <reified T> trySerialize(type: T): String =
move to `JsonRpcSerializer`

2021-12-07 03:28 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/walletconnect/WalletConnectRelay.kt
> +class WalletConnectRelay {
Change the name to `WalletConnectRelayer` to match with the Relayer in the JS project

2021-12-07 04:10 UTC, TalhaAli00 requested changes
just some minor things

2021-12-07 06:04 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/JsonRpcSerializing.kt
> +interface JsonRpcSerializing {
Actually at this point there is no need for interface, good call.

2021-12-07 06:06 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/crypto/CryptoManager.kt
>      fun removeKeys(tag: String)
No, there is no reason :) if you like I can remove those spacse

2021-12-07 06:10 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/utils/JsonRpcMethod.kt
>  object JsonRpcMethod {
Hmm I prefer having the separate file for those constants. The `JsonRpcMethod` is under the same package as `ClientJsonRpcSerializer` so there are close to each other. Also, the `JsonRpcMethod` is used in the `ClientSync` models.

2021-12-07 06:16 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/jsonrpc/utils/ClientJsonRpcSerializer.kt
> +object ClientJsonRpcSerializer {
Yea I like this idea. Having one Serialiser instead of 3 different file is better approach.

2021-12-07 06:19 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/util/UtilFunctions.kt
> +private fun cleanHexPrefix(input: String): String =
this is used to get the hex prefix (0x) on the extension function `hexToUtf8` used to decode encoded message.

2021-12-07 13:09 UTC, TalhaAli00 approved these changes

2021-12-07 13:47 UTC, merged