Feature/sequence expiry
WalletConnect-Labs/WalletConnectKotlinV2 pull request #124
Opened 2021-12-13 21:16 UTC by TalhaAli00

2021-12-14 09:49 UTC, chaak requested changes
One more thing. We should add a check, to every Engine public method the see if under given topic sequence is not expired.

2021-12-14 09:49 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        session.status == SequenceStatus.SETTLED && session.expiry.isSequenceValid()
Ok but what about the Pending Sessions? The Expiry is 24h and it should be handled in `getListOfPendingSessions()`

2021-12-14 09:49 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        session.status == SequenceStatus.SETTLED && session.expiry.isSequenceValid()
+ I cannot find where we set the settled session expiry for 7 days 🤔

2021-12-14 09:49 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        val (listOfExpiredPairing, listOfValidPairing) = storageRepository.getListOfPairingVOs().partition { pairing -> !pairing.expiry.isSequenceValid() }
`!` is not needed

2021-12-14 09:49 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        val (listOfExpiredSession, listOfValidSessions) = storageRepository.getListOfSessionVOs().partition { session -> session.expiry?.isSequenceValid() == false }
`session.expiry?.isSequenceValid()` should be enough

2021-12-14 15:07 UTC, TalhaAli00 commented on walletconnectv2/src/main/AndroidManifest.xml
> +        android:fullBackupContent="@xml/backup_rules" />
So Android applications automatically backup app data and this backup stays even after uninstall. I saw data inside the database even after uninstalling and reinstalling the application. This back policy will ensure that our sensitive files will not be stored locally on the device even after an uninstall

2021-12-14 15:09 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> -        collectClientSyncJsonRpc()
good catch, added back

2021-12-14 15:14 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        val (listOfExpiredPairing, listOfValidPairing) = storageRepository.getListOfPairingVOs().partition { pairing -> !pairing.expiry.isSequenceValid() }
the `!` makes it so the expired pairings are put into the first list. I could remove the `!` and switch the order of the lists if you think that's better

2021-12-14 15:15 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        val (listOfExpiredSession, listOfValidSessions) = storageRepository.getListOfSessionVOs().partition { session -> session.expiry?.isSequenceValid() == false }
Because expiry is nullable, `isSequenceValid()` can return `true`, `false`, and `null`. With nullable Booleans, we have to explicitly state the value we want

2021-12-15 00:59 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +        session.status == SequenceStatus.SETTLED && session.expiry.isSequenceValid()
Settled session expiry is set in the approval logic where the settled session is created using the TTL that's sent with the proposal

2021-12-15 07:53 UTC, chaak approved these changes

2021-12-15 13:33 UTC, merged