Waku_Subscribe request serialization and test
WalletConnect-Labs/WalletConnectKotlinV2 pull request #13
Opened 2021-09-12 04:14 UTC by TalhaAli00

Added waku_subscribe request object with test

2021-09-13 22:05 UTC, ligi requested changes
some minor things I saw when looking over the code - maybe we should also make Expiry and TTL value classes - noticed when seeing the adapter tests

2021-09-14 04:46 UTC, TalhaAli00 commented on walletconnectV2/src/test/kotlin/org/walletconnect/walletconnectv2/common/network/adapters/ExpiryAdapterTest.kt
> +    }
I've removed from current branch. Updates will be in next PR

2021-09-14 05:22 UTC, TalhaAli00 commented
> some minor things I saw when looking over the code - maybe we should also make Expiry and TTL value classes - noticed when seeing the adapter tests

The started off with value classes but there was an issue deserializing the classes. I have left the objects as data classes for now until I get a chance to dig deeper

2021-09-14 05:25 UTC, TalhaAli00 commented on walletconnectV2/src/test/kotlin/org/walletconnect/walletconnectv2/common/network/adapters/ExpiryAdapterTest.kt
> +        val expiry = Expiry(Random.nextLong())
I understand your point and I have updated the code to no longer use Random

2021-09-15 03:10 UTC, merged