* Replaced Ktor with Scarlet for ease of use
WalletConnect-Labs/WalletConnectKotlinV2 pull request #7
Opened 2021-09-01 08:19 UTC by TalhaAli00

* Created the WalletConnectClient (mirror of Client in JS codebase)
* Added the pairing function to WalletConnectClient that accepts a PairParams object containing the Dapp URI
* Added classes to represent the Pairing Proposal, Pairing Approval, and Pairing Reject as per the Out-of-Bound section in the Tech Spec
* Happy path test done for parsing a URI into a Pairing Proposal object
* Sample test included but commented out to show how Scarlet Websocket Client and MockWebServer will communicate during unit tests
* Updated Kotlin to 1.5.30

2021-09-03 08:06 UTC, ligi commented on walletconnectV2/src/main/kotlin/org/walletconnect/walletconnectv2/DefaultWebSocketClient.kt
> +    private fun getServerUrl(): String = if (useTLs) "wss://$hostName:$port" else "ws://$hostName:$port"
```suggestion
    private fun getServerUrl(): String = if (useTLs) "wss://$hostName:$port" else "ws://$hostName:$port"
    private fun getServerUrl(): String = (if (useTLs) "wss" else "ws")+"://$hostName:$port"
```
shorter and easier to spot where the difference is

2021-09-03 09:04 UTC, ligi requested changes
Some nits/suggestions after a shallow review.
Also IMHO we should lower the usage of (companion) objects - sure it's easy but it smells. And can be often just replaced with top level constants/functions. And there is stuff that is just needed for tests leaking into the main codebase (the initLocal thing - can't see use-cases in the lib for consumers for that stuff)

2021-09-07 05:31 UTC, TalhaAli00 commented on sample/build.gradle.kts
> +    implementation("androidx.core:core-ktx:1.3.2")
Default dependencies when creating an android project. I'll review the dependencies once the sample is built and remove this if I don't end up using anything from the dependency.

2021-09-07 05:40 UTC, TalhaAli00 commented
> Some nits/suggestions after a shallow review.
> Also IMHO we should lower the usage of (companion) objects - sure it's easy but it smells. And can be often just replaced with top level constants/functions. And there is stuff that is just needed for tests leaking into the main codebase (the initLocal thing - can't see use-cases in the lib for consumers for that stuff)

@ligi 
The primary reason for containing everything in an object is so functions can be annotated with JvmStatic. One goal while developing the SDK is to have a seamless experience regardless of if the consumer of the SDK is working in a Java file or Kotlin file. The only other way of achieving this would be to have top level functions and then annotate the file with JvmName. I'm not sure if one way is better than the other. I could look into the bytecode java files and see how it looks when going through and optimizing

2021-09-07 05:42 UTC, TalhaAli00 commented on walletconnectV2/src/main/kotlin/org/walletconnect/walletconnectv2/DefaultWebSocketClient.kt
> +        relay.send("".toByteArray())
done

2021-09-07 05:43 UTC, TalhaAli00 commented on walletconnectV2/src/main/kotlin/org/walletconnect/walletconnectv2/DefaultWebSocketClient.kt
> +    private fun getServerUrl(): String = if (useTLs) "wss://$hostName:$port" else "ws://$hostName:$port"
updated in current branch

2021-09-09 08:35 UTC, merged