Feature/implement disconnect method
WalletConnect-Labs/WalletConnectKotlinV2 pull request #90
Opened 2021-11-10 17:52 UTC by chaak

2021-11-10 18:40 UTC, TalhaAli00 commented on sample/src/main/java/org/walletconnect/example/wallet/WalletViewModel.kt
> +class WalletViewModel : ViewModel(), WalletConnectClientListener {
I thought we agreed on having separate interfaces for each function instead of one big one. Was there an issue with going that route?

2021-11-10 18:44 UTC, chaak commented on sample/src/main/java/org/walletconnect/example/wallet/WalletViewModel.kt
> +class WalletViewModel : ViewModel(), WalletConnectClientListener {
Yes and nothing changes. It's in progress at: `feature/implement_diconnect_method`

2021-11-10 18:48 UTC, TalhaAli00 commented on sample/src/main/java/org/walletconnect/example/wallet/ui/SessionsAdapter.kt
> +    RecyclerView.ViewHolder(view) {
This shouldn't be on a new line, it can go back onto line 40

2021-11-11 01:20 UTC, TalhaAli00 requested changes

2021-11-11 01:20 UTC, TalhaAli00 commented on sample/src/main/java/org/walletconnect/example/wallet/ui/SessionsAdapter.kt
>  }
onDisconnect is already made into a final variable in the SessionsAdapter so you don't need to pass it into the view holder. Move the view holder into the adapter class and make it an inner class. Then remove the onDisconnect parameter from the view holder's constructor

2021-11-11 01:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        engineInteractor.approve(proposal, accounts)
revert to using variables

2021-11-11 01:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/client/ClientData.kt
> +)
Are these wallet facing variables?

2021-11-11 01:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    fun approve(proposal: SessionProposal, accounts: List<String>) {
revert

2021-11-11 01:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/sequence/SequenceLifecycleEvent.kt
> +object Default : SequenceLifecycleEvent()
Why not put these inside curly brackets?

2021-11-12 07:22 UTC, chaak commented on sample/src/main/java/org/walletconnect/example/wallet/WalletViewModel.kt
> +    @RequiresApi(Build.VERSION_CODES.N)
I wanted to test conditional removal from list. It's not needed anymore, good call.

2021-11-12 07:28 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/client/ClientData.kt
> +)
Yes

2021-11-12 07:34 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/sequence/SequenceLifecycleEvent.kt
> +object Default : SequenceLifecycleEvent()
If you prefer more inside the curly brackets, yea we can do that :)

2021-11-12 08:36 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/client/ClientTypes.kt
> +    data class ApproveParams(val proposal: SessionProposal, val accounts: List<String>)
Because this approach doesn't take into consideration the storage of sequences. In order to store pairing or session we're gonna need most of the params from the SessionProposal. Therefore, it's better to pass just one object than 10 different parameters within the approval method. Even for the sake of readability.

What's more, I created the `WalletConnectClientData` and `EngineData` sealed classes, to have a clear separation between the wallet facing models which are publicly available and the internal models which are used only inside the sdk.

2021-11-12 08:37 UTC, chaak commented on sample/src/main/java/org/walletconnect/example/wallet/WalletViewModel.kt
> +        val approveParams: ClientTypes.ApproveParams = ClientTypes.ApproveParams(proposal, accounts)
As above ☝️

2021-11-12 08:37 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        engineInteractor.approve(proposal, accounts)
As above ☝️

2021-11-12 08:38 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    fun approve(proposal: SessionProposal, accounts: List<String>) {
See above

2021-11-12 15:24 UTC, TalhaAli00 commented on sample/src/main/java/org/walletconnect/example/wallet/ui/SessionsAdapter.kt
> +        fun bind(session: WalletConnectClientData.SettledSession) = with(binding) {
Since you're using with on line 38, you don't need to create the binding variable. `SessionItemBinding.bind(view)` will go inside the with

2021-11-12 15:32 UTC, TalhaAli00 commented on sample/src/main/java/org/walletconnect/example/wallet/ui/SessionsAdapter.kt
> +        fun bind(session: WalletConnectClientData.SettledSession) = with(binding) {
remove the binding variable. Since you're using `with` on line 38, you don't need the variable anymore. Just replace `binding` on line 38 with the `SessionItemBinding` object

2021-11-12 15:33 UTC, TalhaAli00 approved these changes

2021-11-13 11:39 UTC, merged