Feature/handle json rpc errors
WalletConnect-Labs/WalletConnectKotlinV2 pull request #92
Opened 2021-11-12 12:58 UTC by chaak

Should wait until the `Feature/implement disconnect method` is merged

2021-11-17 04:36 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        pairingListener = listener
This is never used, what is its purpose?

2021-11-17 04:36 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        sessionApproveListener = listener
same, never used

2021-11-17 04:36 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        sessionRejectListener = listener
Same, never used

2021-11-17 04:37 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        sessionDeleteListener = listener
Same, never used

2021-11-17 04:38 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +    private var sessionDeleteListener: WalletConnectClientListeners.SessionDelete? = null
These are never used

2021-11-17 04:42 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
>              }
Instead of doing this in init, move the launch code inside the  `setWalletConnectListener` method

2021-11-17 04:42 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +    private var walletConnectListener: WalletConnectClientListener? = null
This will no longer be needed after moving `launch` code

2021-11-17 04:44 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
>                      else -> SequenceLifecycleEvent.Unsupported
This case is never used

2021-11-17 04:55 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                val message: String = codec.decrypt(encryptionPayload, sharedKey)
Change to `decryptedMessage` so it's understood at a quick glance

2021-11-17 04:58 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
>                  }
What is this trying to do?

2021-11-17 05:00 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                jsonRpcSerializer.tryDeserialize(Request::class.java, message)?.let { request ->
We need a more descriptive name than Request

2021-11-17 05:03 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                val encryptionPayload = relayRequest.encryptionPayload
instead of creating the `encryptionPayload` variable and hiding the extension function inside the model class, just move the logic here. That logic is not being shared anywhere else so there's no real benefit in hiding the `toEncryptionPayload()`  inside the `Relay.Subscription.Request` object

2021-11-17 05:06 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
>                  }
Instead of using nested `let`s to show the different cases, just use if/else. Scoped function are great but we need to be careful not to abuse them

2021-11-17 05:16 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/serailising/JsonRpcSerialising.kt
> +interface JsonRpcSerialising {
Why an interface?

2021-11-17 05:17 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/serailising/JsonRpcSerializer.kt
> +        }
Remove the interface and replace the `tryDeserialize` function with an inline function

```suggestion
        inline fun <reified T> tryDeserialize(json: String): T? {
        return runCatching { moshi.adapter(T::class.java).fromJson(json) }.getOrNull()
    }
```

2021-11-17 05:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        this.walletConnectListener = walletConnectListener
Replace this with the `launch` code from above

2021-11-17 05:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        pairingListener = listener
This isn't needed

2021-11-17 05:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        sessionApproveListener = listener
This isn't needed

2021-11-17 05:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        sessionRejectListener = listener
This isn't needed

2021-11-17 05:20 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        sessionDeleteListener = listener
This isn't needed

2021-11-17 05:24 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    fun pair(uri: String, onResult: (Result<Any>) -> Unit) {
Change `Result<Any>` to `Result<String>`

2021-11-17 05:28 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +                onSuccess = { topic -> listener.onSuccess(WalletConnectClientData.SettledPairing(topic as String)) },
Remove cast after updating `EngineInteractor.pair`

2021-11-17 05:30 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    fun approve(proposal: EngineData.SessionProposal, accounts: List<String>, onResult: (Result<Any>) -> Unit) {
change `Result<Any>` to `Result<EngineData.SettledSession>`

2021-11-17 05:31 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +                onSuccess = { settledSession -> listener.onSuccess((settledSession as EngineData.SettledSession).toClientSettledSession()) },
Remove cast after updating `EnginerInteractor.approve`

2021-11-17 05:37 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    fun reject(reason: String, topic: String, onResult: (Result<Any>) -> Unit) {
change `Result<Any>` to `Result<String>` after updating `observePublishAcknowledgement`

2021-11-17 05:38 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +                onSuccess = { topic -> listener.onSuccess(WalletConnectClientData.RejectedSession(topic as String)) },
Remove cast after updating `EngineInteractor.reject`

2021-11-17 05:40 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    fun disconnect(topic: String, reason: String, onResult: (Result<Any>) -> Unit) {
Change `Result<Any>` to `Result<String>` after updating `observePublishAcknowledgement`

2021-11-17 05:44 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    private fun observePublishError(onResult: (Result<String>) -> Unit) {
Change function to accept generic
```suggestion
    private fun <T> observePublishError(onResult: (Result<T>) -> Unit) {
```

2021-11-17 05:48 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                .catch { exception -> Timber.tag("WalletConnect exception").e(exception) }
What are you trying to achieve with catch? `catch` completes the collection once it's been called

2021-11-17 05:49 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                    cancel()
I don't think you want `cancel` here. Cancel will actually cancel the nearest scope which will actually cancel the WC scope on line 192

2021-11-17 05:51 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    private fun observePublishAcknowledgement(onResult: (Result<Any>) -> Unit, result: Any) {
Change the function to accept `Result<T>`
```suggestion
    private fun <T> observePublishAcknowledgement(onResult: (Result<T>) -> Unit, result: T) {
```

2021-11-17 05:51 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                .catch { exception -> Timber.tag("WalletConnect exception").e(exception) }
Same question as above

2021-11-17 05:52 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                    cancel()
again, I don't think you want `cancel` here

2021-11-17 05:55 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/serailising/JsonRpcSerializer.kt
> +        moshi.adapter(typeClass).toJson(type)
Similar comment as below. Using `reified` will simply the function signature
```suggestion
    inline fun <reified T> trySerialize(type: T): String =
        moshi.adapter(T::class.java).toJson(type)
```

2021-11-17 05:58 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepository.kt
>              }
replace `map` with `onEach`. Then you won't have to return `relayRequest` on line 63 and it will better describe what is happening

2021-11-17 06:08 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/data/model/Relay.kt
> +            val encryptionPayload: EncryptionPayload = params.subscriptionData.message.toEncryptionPayload()
as per the comment above, move this to the call site. Abstracting the extension function doesn't provide any noticeable benefit

2021-11-17 06:10 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/data/model/Request.kt
> +    val method: String?
We need a better name for this object. We have a lot of request objects

2021-11-17 06:12 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +                onSuccess = { topic -> listener.onSuccess(WalletConnectClientData.DeletedSession(topic as String)) },
Remove cast after updating `EngineInteractor.disconnect`

2021-11-17 06:13 UTC, TalhaAli00 requested changes
Let me know if you have any questions about the comments

2021-11-17 08:12 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                jsonRpcSerializer.tryDeserialize(Request::class.java, message)?.let { request ->
Change to JsonRpcRequest should be enough

2021-11-17 08:20 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                val encryptionPayload = relayRequest.encryptionPayload
The goal here is better readability. 
I prefer having short invocation of given field, than the chain of parameters calling one another.
Extension invocation moved to the Engine.

2021-11-17 09:03 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/serailising/JsonRpcSerializer.kt
> +        }
Good call. I like this approach with inline function and refined keyword more.

2021-11-17 09:03 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/serailising/JsonRpcSerialising.kt
> +interface JsonRpcSerialising {
With the inline function approach interface is not needed anymore.

2021-11-17 09:32 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        pairingListener = listener
Damn right, pairingListener var is not used

2021-11-17 09:34 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        this.walletConnectListener = walletConnectListener
Could you elaborate?

2021-11-17 09:39 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    private fun observePublishError(onResult: (Result<String>) -> Unit) {
Good call.

2021-11-17 09:40 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +    private fun observePublishAcknowledgement(onResult: (Result<Any>) -> Unit, result: Any) {
Good call

2021-11-17 09:41 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/data/model/Relay.kt
> +            val encryptionPayload: EncryptionPayload = params.subscriptionData.message.toEncryptionPayload()
See the comment above

2021-11-17 09:54 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                .catch { exception -> Timber.tag("WalletConnect exception").e(exception) }
Yes, that is correct. It may be a bit overzealous, but the goal is to handle any network error other than what is returned by json rpc.

2021-11-17 10:03 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                    cancel()
Oh I do need a cancel here. This method is responsible for observing the response of particular publish request. Every time when we got the acknowledgement we want to return the result and cancel scope to avoid overlapping any other publish responses.

2021-11-17 10:04 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                    cancel()
Same

2021-11-17 10:13 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectClient.kt
> +        this.walletConnectListener = walletConnectListener
I haven't noticed the comments above, it's all clear.

2021-11-17 18:39 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                .catch { exception -> Timber.tag("WalletConnect exception").e(exception) }
have you been able to get the `catch` to work?

2021-11-17 18:41 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                    cancel()
Putting cancel here will actually cancel the WalletConnect global scope. You want to wrap the `onResult` and `cancel()` inside a `superviosrScope` lambda. That way the cancel is isolated to it's own separate scope and won't affect another other existing scopes

2021-11-17 19:24 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                .catch { exception -> Timber.tag("WalletConnect exception").e(exception) }
Resolved on DMs. This case is about catching the scarlet networking errors

2021-11-18 16:44 UTC, TalhaAli00 commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/WalletConnectClientIntegrationAndroidTest.kt
> +                            assert(false)
also call `activityRule.close()` here

2021-11-18 16:44 UTC, TalhaAli00 commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/WalletConnectClientIntegrationAndroidTest.kt
> +                    assert(true)
call `activityRule.close()` to close the thread

2021-11-18 16:45 UTC, TalhaAli00 commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/WalletConnectClientIntegrationAndroidTest.kt
> +                    assert(false)
call `activityRule.close()` to close the thread

2021-11-18 16:45 UTC, TalhaAli00 commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/WalletConnectClientIntegrationAndroidTest.kt
> +                    Logger.log("Pairing success")
replace logger with assert

2021-11-18 16:45 UTC, TalhaAli00 commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/WalletConnectClientIntegrationAndroidTest.kt
> +                    Logger.log("Pairing error: $error")
replace logger with assert

2021-11-18 16:52 UTC, TalhaAli00 approved these changes
Make those last changes and you're good to go. A note for the future, we should try to keep changes on merged in code to a minimum as much as possible. If there are changes needed, let's make sure to address them in PRs instead.

2021-11-19 08:10 UTC, merged