Feature/fix integration test
WalletConnect-Labs/WalletConnectKotlinV2 pull request #95
Opened 2021-11-16 06:47 UTC by TalhaAli00

2021-11-16 07:05 UTC, chaak commented on walletconnectV2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/jsonrpc/JsonRpcEvent.kt
> +sealed class JsonRpcEvent {
We have already in project `SequenceLifecycleEvent`, pls use it and delete `JsonRpcEvent`

2021-11-16 07:06 UTC, chaak commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/PairingIntegrationAndroidTest.kt
> +import java.util.concurrent.CountDownLatch
Unused imports

2021-11-16 07:07 UTC, chaak commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/IntegrationTestApplication.kt
> +import timber.log.Timber
Unused imports

2021-11-16 07:08 UTC, chaak commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/WCIntegrationActivityScenarioRule.kt
> +fun wcActivityScenarioRule(intentSupplier: () -> Intent): WCIntegrationActivityScenarioRule =
This fun is unused, should be deleted then

2021-11-16 07:09 UTC, chaak commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/WCTestRunner.kt
> +class WCTestRunner: AndroidJUnitRunner() {
This class is unused, should be deleted then

2021-11-16 07:10 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/WalletConnectScope.kt
>  import timber.log.Timber
Delete

2021-11-16 07:17 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +            .filterIsInstance<WebSocket.Event.OnConnectionOpened<*>>()
This line affects the pairing flow. We are able to do only one pairing just after app launch, because `OnConnectionOpened` event is received only during the Scarlet initialisation. It's not possible to do more than one pairing.

2021-11-16 07:22 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepository.kt
>              WakuRelayRepository(useTls, hostName, apiKey, application)
Since we don't need application in Scarlet, we can delete this variable

2021-11-16 07:22 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/util/Logger.kt
> +object Logger {
👌

2021-11-16 07:23 UTC, chaak commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepositoryTest2.kt
> +internal class WakuRelayRepositoryTest2 {
`WakuRelayRepositoryTest2`? What about the `WakuRelayRepositoryTest1`? :)

2021-11-16 07:26 UTC, chaak commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/relay/data/model/RelayTest.kt
>      }
What about this class? Every test case is uncommented.

2021-11-16 07:27 UTC, chaak requested changes
That's all from my side

2021-11-16 12:39 UTC, chaak requested changes

2021-11-16 12:39 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepository.kt
> +//            .lifecycle(AndroidLifecycle.ofApplicationForeground(application)) // Maybe have debug version of scarlet w/o application and release version of scarlet w/ application once DI is setup
Pls add TODO here. We're gonna have to find the solution how to manually manage the  Scarlet connection status when app goes background and foreground to avoid getting messages when app hits onPause.

2021-11-16 20:07 UTC, TalhaAli00 commented on walletconnectv2/src/androidTest/kotlin/org/walletconnect/walletconnectv2/WCTestRunner.kt
> +class WCTestRunner: AndroidJUnitRunner() {
This is actually being used in the build.gradle file. It's the new test runner

2021-11-17 03:47 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +            .filterIsInstance<WebSocket.Event.OnConnectionOpened<*>>()
Good catch. I've updated the logic to rely on a new stream

2021-11-17 03:49 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepository.kt
>              WakuRelayRepository(useTls, hostName, apiKey, application)
We do still need it. Application should only be commented out during integration testing. We will need to create two separate instance of WakuRelay, one in the debug directory without Applicaiton and one in the release directory that uses Application. I've updated my comment with a TODO

2021-11-17 03:55 UTC, TalhaAli00 commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepositoryTest2.kt
> +internal class WakuRelayRepositoryTest2 {
I've removed the WakuRelayRepositoryTest2 class and now we only have one.

2021-11-17 03:58 UTC, TalhaAli00 commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/relay/data/model/RelayTest.kt
>      }
Since the eventStream variable was removed from the Repository and replaced with eventFlow, it broke this whole test. We will need to go back and fix this once we get a chance.

2021-11-17 03:58 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepository.kt
> +//            .lifecycle(AndroidLifecycle.ofApplicationForeground(application)) // Maybe have debug version of scarlet w/o application and release version of scarlet w/ application once DI is setup
Added TODO

2021-11-17 07:56 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/relay/WakuRelayRepository.kt
>              WakuRelayRepository(useTls, hostName, apiKey, application)
Got it, so please uncomment:
`//            .lifecycle(AndroidLifecycle.ofApplicationForeground(application))` in WakuReleayRepository.

As you said, it should be commented only during the integration tests. On develop, the application lifecycle is required.

2021-11-17 08:01 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/engine/EngineInteractor.kt
> +                .onEach {
Named variable would be nice in here

2021-11-17 08:03 UTC, chaak approved these changes
Approved. Pls add named variable and uncomment the app lifecycle in WakuRespository before merging to develop.

2021-11-17 18:21 UTC, merged