Feature/generic payloads
WalletConnect-Labs/WalletConnectKotlinV2 pull request #98
Opened 2021-11-19 04:51 UTC by TalhaAli00

2021-11-19 10:45 UTC, chaak commented on sample/src/main/java/org/walletconnect/example/payloads/EthSendTransaction.kt
> +data class EthSendTransaction(
If not used should be deleted

2021-11-19 10:45 UTC, chaak commented on sample/src/main/java/org/walletconnect/example/payloads/EthSign.kt
> +data class EthSign(
Same

2021-11-19 10:50 UTC, chaak commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/client/WalletConnectClientData.kt
> +//        @ExperimentalStdlibApi
Again, we shouldn't keep code which is commented

2021-11-19 10:54 UTC, chaak commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/GenericPayloadsTest.kt
> +
What about this class? If it's not relied to our production code it should be deleted. It creates only confusion. When we go back to the generic adapter issue we're gonna start from scratch anyways.

2021-11-19 10:54 UTC, chaak requested changes
See below my comments

2021-11-21 22:28 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/org/walletconnect/walletconnectv2/client/WalletConnectClientData.kt
> +//        @ExperimentalStdlibApi
agreed

2021-11-21 22:30 UTC, TalhaAli00 commented on walletconnectv2/src/test/kotlin/org/walletconnect/walletconnectv2/GenericPayloadsTest.kt
> +
so I don't want to lose the train of thought with the work that was started. Once we come back to it, we can remove it if there's another approach we want to take

2021-11-22 08:22 UTC, chaak approved these changes

2021-11-25 01:54 UTC, merged